### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by numberZero** [MarkuBu/vec3d#1]
The work “methode” does not exist (in English at least).
Also, please use other words (“way,” “option,” whatever else) when you don’t mean OOP methods, the current use is a bit confusing.

**Comment by MarkuBu** [comment]
Ok, thanks. Will change it.

**Comment by MarkuBu** [comment]
Hope this is better

**Comment by numberZero** [comment]
oh well, I seem to have to make a PR myself...

**Comment by MarkuBu** [comment]
I'm sorry for my bad English
