### ISSUE TITLE
Non-numerical vectors

### ISSUE THREAD

**Issue by numberZero** [MarkuBu/vec3d#2]
https://github.com/MarkuBu/vec3d/blob/master/init.lua#L134
`vec3d.new` happily creates a vector of e.g. tables or strings if (accidentally) called with such arguments.

**Comment by MarkuBu** [comment]
Hm? What do you mean?

**Comment by numberZero** [comment]
Actually strings don’t seem to create any problems, Lua converts them itself when necessary. The only exception I noticed is equality comparison, `vec3d("1", "2", "3") ~= vec3d(1, 2, 3)`. But anything like `vec3d("(1, 2, 3)")` or `vec3d(1, {2}, 3)` creates an invalid vector on which virtually any operation throws. IMO it should convert arguments to numbers on construction.

**Comment by MarkuBu** [comment]
I don't want to put to much code for checking and conversion to the library.
