### ISSUE TITLE
Angles

### ISSUE THREAD

**Issue by numberZero** [MarkuBu/vec3d#3]
`vec3d.angle_between` is confusing. It should be called e.g. `vec3d.angle_2d_oriented`.
And `vec3d.angle_between` should return non-oriented angle between 3d vectors.
That is, `acos( 〈a, b〉/(|a|⋅|b|) )`

**Comment by MarkuBu** [comment]
> -- returns the angle between two 2d vectors (x,z) in radians
> -- y from a 3d vector is ignored

angle_between is a 2d function, as described in the code. It uses 3d vectors as parameters, but y is ignored

**Comment by MarkuBu** [comment]
Renamed to `angle_between_2d`
