### ISSUE TITLE
vec3d:is_between is broken

### ISSUE THREAD

**Issue by numberZero** [MarkuBu/vec3d#4]
1. It is undocumented.
2. It seems to assume `ab` and `ap` to be normalized.
3. It uses `abs` thus ignoring direction.

What did you want to do?

**Comment by numberZero** [comment]
Note: after trivial fixes, your function looks like
```lua
function vec3d:is_between(a, b)
        local ab = b - a
        local ap = self - a
        local lp = ap:len()
        local lb = ab:len()
        local dot = ap:dot(ab) / (lp * lb)
        return lp < lb and dot > 0.95
end
```
This is not the best way anyway, but it seems to work somehow.

**Comment by MarkuBu** [comment]
Doc is not complete and I still work on some functions

**Comment by MarkuBu** [comment]
Thanks for the fix. Will try it out. This function is based on the answer to my question on stackoverflow. 

http://stackoverflow.com/questions/43634465

**Comment by MarkuBu** [comment]
Scalar projection may also be broken. I'm still not sure if it is working as expected.

**Comment by numberZero** [comment]
That answer at http://stackoverflow.com/questions/43634465 is wrong. Check my one.

> Scalar projection may also be broken

It seems fine. There are several ways to project one vector onto another one; the one you chose is totally legitimate.

**Comment by MarkuBu** [comment]
Ok, thanks. Will try it as soon I have time
